language: python
matrix:
  include:
    - python: 3.3
      env: TOXENV=py33-django18
    - python: 3.4
      env: TOXENV=py34-django18
    - python: 3.5
      env: TOXENV=py35-django18
    - python: 3.4
      env: TOXENV=py34-django19
    - python: 3.5
      env: TOXENV=py35-django19
    - python: 3.4
      env: TOXENV=py34-django110
    - python: 3.5
      env: TOXENV=py35-django110
    - python: 3.4
      env: TOXENV=py34-django111 
    - python: 3.5
      env: TOXENV=py35-django111 
    - python: 3.4
      env: TOXENV=py34-django20
    - python: 3.5
      env: TOXENV=py35-django20

install:
  - pip install "pip<8.0.0"
  - pip install tox
script:
  - tox
